### ISSUE TITLE
Input without mapping is overwritten in some circumstances

### ISSUE THREAD

**Issue by deepestblue** [ratreya/Lipika_IME#10]
I found this weird issue while testing your suggestion regarding pull request 9. I'm not sure if the issue is in the code or in the schemas. If the latter, I'd still like help :-)

* Switch to ISO-15919 (also reproducible with IPA)
* Type the following key-sequence B-a-backspace-i
* Expected: 'Bi'
* Actual: 'i'
* The 'B' seems to be being overwritten when the 'i' is typed. This doesn't happen if instead of the 'B', there was an input which has a mapping in the scheme, like, say 'b'. Typing b-a-backspace-i does result in the expected 'bi'.

**Comment by ratreya** [comment]
Confirmed bug in code and pushed out a fix with the latest binary. Check it out..
Thanks for reporting!

**Comment by deepestblue** [comment]
Confirmed fixed. Thanks!
