### ISSUE TITLE
zwj & zwnj mappings

### ISSUE THREAD

**Issue by omshivaprakash** [ratreya/Lipika_IME#15]
Hi Atreya, 

May I know which key zwj and zwnj (U+200D & U+200C) are mapped for kannada? Tried figuring out but no quick luck. Hope you can respond quickly on that. 

Thanks
Shivu

**Comment by ratreya** [comment]
In all transliteration schemes it is ^ and ^^ for zwj and zwnj respectively. For example, [here's where you can find it](https://github.com/ratreya/Lipika_IME/blob/master/Common/Resources/Schemes/Transliteration/Baraha.tlr#L82-L83) for Baraha.
