### ISSUE TITLE
nudi layout for Kannada

### ISSUE THREAD

**Issue by MayuraVerma** [ratreya/Lipika_IME#16]
Hello,

Is it possible to add nuDi layout  scheme for Kannada layout.

**Comment by ratreya** [comment]
NuDi is a Keyboard Layout and not a Transliteration scheme. As such, it is better suited for Apple's own build-in keyboard layout for Kannada. Apple's build-in Kannada keyboard layout is very close to NuDi already. You can use [Ukelele](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) to further edit this Keyboad Layout to match your taste.

**Comment by bengulurumanjunatha** [comment]
@ratreya Are you needing help developing this keyboard layout?

Please let me know I can assist.

Can lipika-ime host .keylayout file?

**Comment by ratreya** [comment]
You can try this: https://github.com/MayuraVerma/KPRao-KGP-Keyboard-Layout-for-Mac
Keyboard layouts are supported natively on Mac OS X. You don't need LipikaIME.
