### ISSUE TITLE
Kannada Dictionary

### ISSUE THREAD

**Issue by MayuraVerma** [ratreya/Lipika_IME#17]
Google input tools has Kannada dictionary. But this tool doesn't have the dictionary. I see there is a dictionary.raw in the google input tool. Please try to add dictionary to this tool

**Comment by ratreya** [comment]
I am pretty sure the licensing on Google's internal dictionary does not support copyleft reuse. However, this is a nice-to-have feature - will consider supporting in the future.

**Comment by MayuraVerma** [comment]
I have pretty decent Kannada dictionary in hunspell format. Is it possible to add this dictionary for suggestion list in this keyboard?

When I use this keyboard, there is a dropdown menu, which shows suggestions. But this is limited to one word.
