### ISSUE TITLE
Suggestion bar

### ISSUE THREAD

**Issue by MayuraVerma** [ratreya/Lipika_IME#18]
I have pretty decent Kannada dictionary in hunspell format. Is it possible to add this dictionary for suggestion list in this keyboard?

When I use this keyboard, there is a dropdown menu, which shows suggestions. But this is limited to one word.

**Comment by ratreya** [comment]
The current dropdown is not a suggestion. It is the actual string in the target language that you have typed so far. I am not inclined to add a one-off dictionary at this time. I will ping you offline if this is something I get around to doing in the future.

**Comment by MayuraVerma** [comment]
Any news on the suggestion bar. yet?

**Comment by ratreya** [comment]
Nothing yet. I have been busy releasing this for iOS - [LipikaBoard](https://itunes.apple.com/us/app/lipikaboard/id1224483004).
