### ISSUE TITLE
Nuqta consonants and vowels

### ISSUE THREAD

**Issue by dalahast** [ratreya/Lipika_IME#19]
I've just started using LipikaIME and can't seem to find a way to enter some nuqta consonants with vowels correctly. With transliteration set to ITRANS, I can type `.Dhi` and get ढ़ि as expected. Typing `.Di` results in ऱि instead of the expected ड़ि; indeed, I can't find any way to type ड़ि with LipikaIME. Typing `Dz` gives ड़्, but `Dzi` gives ड़्इ, without properly attaching the vowel. Additionally, the output of `Ra` and `.Da` is the same, but `Rha` does not seem to exist as an alternate for `.Dha`, as it should.

As I understand, ऱ is used for transcribing the Dravidian alveolar R in Devanāgarī, so ड़ should be the output of `Ra` and `.Da`. I suppose one fix would be to change RRA in Devanagari.map to 095C instead of 0931, but that doesn't solve the issue of vowels not properly attaching to "manual" nuqta consonants (e.g. attaching a vowel after typing `.z` to add the nuqta).

**Comment by ratreya** [comment]
As I said in Issue #5, the Unicode glyph name RRA is inconsistent for Devanagari. To fix the Nukta attachment issue, can you please edit /Library/Input Methods/LipikaIME.app/Contents/Resources/Schemes/Default.ime and add the following at line 5:

`
{CONSONANT}{SIGN/NUKTA}{DEPENDENT}	[CONSONANT][SIGN/NUKTA][DEPENDENT]
`
Then restart your computer and try it out. Let me know how that works. If it works well for you, I will make that change in the application binary.

**Comment by ratreya** [comment]
The only problem I found was that D.a does not work, you have to type Da. to get the desired output. Everything else seems to work. But please try it out and confirm.

**Comment by dalahast** [comment]
I've added the line (Github seems to have replaced the tab character with a space, which initially caused LipikaIME to beep and not load correctly, but I fixed it) and ran `killall LipikaIME` from Terminal to restart the IME without having to restart the entire system. I also previously edited the transliteration schemes to output ड़ for these combinations, which means I can easily get (e.g.) ड़, ड़ि, ड़ी, without inputting the nuqta manually.

Currently, I get the following when inputting the nuqta manually:
ड् for `Dza`
ड़ for `Daz`
ड़ि for `Dzi`
डि़ for `Diz`
ड़ो for `Dzo`
डो़ for `Doz`
This confirms the behavior you observed with having to place the modifier at the end of the sequence for ड़ (likely because ड is internally seen as "unmodified" as opposed to e.g. डि `Da + i`).

**Comment by ratreya** [comment]
Actually, make the following changes and it should all work correctly: 5309fde7fd5e37cd6de2df5bf5261e7576d8e1b5

**Comment by dalahast** [comment]
That seems to have fixed it, thanks. Typing the nuqta modifier immediately after the consonant works for any combination now (so `Dza` now correctly outputs ड़).

With the modified Devanāgarī mapping for RRA, this also means that ऱ is still easily accessible through `rza`.

**Comment by ratreya** [comment]
Perfect - thanks for confirming. I will close the issue after the change makes it into the next release.

**Comment by ratreya** [comment]
There were some lingering issues with the fix above. It did not work for Hindi and for languages that did not have a Nukta defined. All of this is fixed in: 2ab8e41b46d6f44db196d2d2e382f506291f0297.
