### ISSUE TITLE
Unifying LA across scripts

### ISSUE THREAD

**Issue by dalahast** [ratreya/Lipika_IME#21]
I recently observed that the only way to input the Tamil consonant ல் in LipikaIME is to switch to Ksharanam transliteration and type `Ll` or `lL`. I thought it was strange that a consonant should only be accessible in one transliteration scheme, so I did some further research.

* The source of the Ksharanam transliteration scheme is [here](http://blog.ambari.sh/2014/03/a-custom-keymap-for-indian-languages.html). The different inputs for Tamil ல் and Devanāgarī ल् appear to stem partially from differences in Sanskrit and Tamil pronunciation, and partially from the author's mistaken interpretation of ISO 15919, which prescribes different representations for these consonants than are given in the tables (e.g. the author gives `ḻ` for Tamil ல், when ISO 15919 uses it for ழ instead).
* One might expect `l` to produce ல் when typing Tamil in Baraha transliteration; [Baraha's documentation](http://www.baraha.com/help/Keyboards/tam_phonetic.htm) indicates that this is the correct way to type ல் using their input method. Despite this, typing `la` with LipikaIME set to Baraha > Tamil instead produces lஅ, a Latin letter followed by a Tamil vowel.
* When typing Kannada and Telugu, Dravidian languages with phonologies resembling that of Tamil, typing `la` in, say, Baraha, produces the expected output. For example, `la` in Baraha > Telugu produces ల, not lఅ (as could be expected based on the Tamil behavior).

Is there some other reason to single out ல as "LLLLA" in the input schemes? From what I can tell, it's only used for Tamil, and is superfluous; instead, "LA" should be mapped to ல in Tamil.

**Comment by ratreya** [comment]
Baraha and other non-Ksharanam transliteration schemes not working correctly for Tamil is a bug. I believe this commit: c126c6cda76c60e5c12d63f3777abc7c0a65a718 should fix it. Please apply it to your local copy.

**Comment by dalahast** [comment]
Confirmed. After updating the contents of Tamil.map and deleting the now-obsolete Tamil with Grantha.map, the input works as expected, bringing the Tamil input behavior in line with the behavior for other Dravidian scripts (and in line with the transliteration standards).

**Comment by ratreya** [comment]
Thanks for confirming!
